language: ruby

rvm:
  - 2.7.3

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rails db:seed
  - bundle exec rails webpacker:compile
  - bundle exec rails test test/models/usuario_test.rb
  - bundle exec rails test test/models/entrega_interna_test.rb
  - bundle exec rails test test/models/encomenda_test.rb
  - bundle exec rails test test/models/entrega_externa_test.rb
  - bundle exec cucumber features/entrega_externa.feature
  - bundle exec cucumber features/entrega_interna.feature

services:
  - postgresql